FROM ubuntu:16.04
LABEL maintainer="michael.j.apostolides@gmail.com"
ENV DEBIAN_FRONTEND noninteractive
# INSTALL BASE REQUIREMENTS
RUN apt-get update && \
    apt-get install -y git sudo apache2 python2.7 
RUN apt-get install -y python-pip 

# Update and install system libraries
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends  \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    gcc \
    mono-mcs \
    build-essential \
    cmake \
    less \
    libbamtools-dev \
    libboost-dev \
    libboost-iostreams-dev \
    libboost-log-dev \
    libboost-system-dev \
    libboost-test-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libz-dev \
    nano \
    pandoc && \
    rm -rf /var/lib/apt/lists/*

#RUN apt-get install -y libbz2-dev liblzma-dev
RUN pip install pysam==0.15.3
RUN pip install numpy==1.16.5
RUN pip install pandas==0.24.2
RUN pip install bedtools==2.27
