
#https://hub.docker.com/r/jsschrepping/velocyto-docker/dockerfile

FROM continuumio/miniconda2:4.7.12
LABEL maintainer="michael.j.apostolides@gmail.com"
ENV DEBIAN_FRONTEND noninteractive
# INSTALL BASE REQUIREMENTS
